### PR TITLE
Updated spanish translation

### PR DESCRIPTION
**Pull request by bilthon**
## Description
Providing some missing spanish translations

## Motivation and Context
Increases the translation coverage for spanish

## How Has This Been Tested?
Only string resources were changed, so no tests are required (right?) other than it compiles.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [Contribution document](../docs/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by michaelWuensch** [comment]
Hi Nelson, thanks a lot for the update!
For the sake of simplicity we manage translations with crowdin, so everyone can translate without needing any coding skills.

I'll see if I can import the updated spanish xml there, so you don't have to reenter it in crowdin.

It would be cool, if you could use crowdin directly for future translations.

**Comment by bilthon** [comment]
Hey there! sorry I wasn't aware of that. I can submit it via crowdin if needed.

**Comment by michaelWuensch** [comment]
Yes, that would be awesome, thanks!

**Comment by bilthon** [comment]
Ok done. I guess we can close this PR then right?

**Comment by michaelWuensch** [comment]
Yes, thank you very much! A lot of people will love this!
I am closing the Issue now.

**Pull request closed without merging**
