### PR TITLE
Create and Update some Finnish translations on strings.xml

### PR DESCRIPTION
**Pull request by tlindi**

### CODE REVIEW

**Comment by michaelWuensch** [comment]
@tlindi thanks for your Contribution!

As stated in the translation guidelines I will only merge the PR if you finish the whole translation. Sorry.
For translating just a few lines you are required to use crowdin.

Here is a quote from the guidelines:
"If you are dedicated and do the complete translation of the app, you can also submit a pull request directly. Incomplete translation pull requests will be rejected as merging and syncing with crowdin causes unnecessary work for the maintainers. So if you just want to translate a few strings, please use crowdin."

**Comment by tlindi** [comment]
@michaelWuensch ok, Will make complete translation. And new PR?

**Comment by michaelWuensch** [comment]
@tlindi awesome, thanks!
You can keep the PR open and just add commits to it.
Leave a comment when you are done :)

**Comment by tlindi** [comment]
> @tlindi awesome, thanks! You can keep the PR open and just add commits to it. Leave a comment when you are done :)

Translations completed.

**Comment by tlindi** [comment]
5fbbd7c has few typofixes

**Comment by michaelWuensch** [comment]
You are the man! 
Thank you so much for doing this.
I'll try to get it merged and do a released this week, but can't promise if I'll find the time to do it.

**Pull request merged**
