### PR TITLE
Add specific zero-amount-payment-request error message

### PR DESCRIPTION
**Pull request by vindard**
## Description
This PR introduces a more specific error message for the error case where a payment requests has an invalid zero-amount attached to it.

The prior error message suggests a more general and broad failure of the payment request that is very difficult to understand and correct by the end-user.

_**Note:** The original error code was removed in a separate commit since it no longer is used anywhere else. If this isn't ok, we can simply drop that commit and force-push the branch (or revert the specific commit)_

## Motivation and Context
Issue:  #363 

## How Has This Been Tested?
Has not been tested

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [Contribution document](../docs/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by vindard** [comment]
I just found a similar issue/fix across in the Zap-Desktop repo: https://github.com/LN-Zap/zap-desktop/pull/3385

**Comment by michaelWuensch** [comment]
@vindard 
Hi, thank you very much for the pull request!
The old message is indeed confusing.
Can you please use the wording from Zap desktop?
I like it more as it explains why 0 amount invoices are not supported.

**Comment by vindard** [comment]
> @vindard
> Hi, thank you very much for the pull request!
> The old message is indeed confusing.
> Can you please use the wording from Zap desktop?
> I like it more as it explains why 0 amount invoices are not supported.

Sure no probs, change made [here](https://github.com/LN-Zap/zap-android/pull/364#event-5359925168)

**Comment by michaelWuensch** [comment]
@vindard
Ah sorry, i just looked at the screenshot of that pull request you linked which showed another message that I actually meant.  And I like more:

"This is a zero amount payment request. Zap does not support zero amount payment requests due to security concerns associated with them."

Would you mind changing it again? I want to explain why we don't support them, not just say it is unsupported.

**Comment by vindard** [comment]
> @vindard
> Ah sorry, i just looked at the screenshot of that pull request you linked which showed another message that I actually meant. And I like it more:
> 
> "This is a zero amount payment request. Zap does not support zero amount payment requests due to security concerns associated with them."
> 
> Would you mind changing it again? I want to explain why we don't support them, not just say it is unsupported.

Ah makes sense, changed [here](https://github.com/LN-Zap/zap-android/pull/364#event-5361528227)

**Review by michaelWuensch — APPROVED** [review]

**Pull request merged**
