### PR TITLE
Add "Bulgarian" language option

### PR DESCRIPTION
**Pull request by Relaxo143**
## Description

This is a simple change which allows users to use Zap in Bulgarian, even if their system language is different.

## Motivation and Context

Many Bulgarians use English as their system language, but could still like to use the wallet in their mother tongue.
Addresses #129

## How Has This Been Tested?

Tested using the emulator on Android Studio (Pixel 2 API 28 Android 9.0 1080*1920 )

## Screenshots (if appropriate):
zappull

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [Contribution document](../docs/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Unfortunately I introduced a bug. I was really hoping I could implement this completely on my own. However, I could not solve this issue. Once "Bulgarian" is selected and the app restarts it crashes if the settings are opened. Everything else seems to work fine. This is what I got from the debugger: https://pastebin.com/xRG2zjUz 

I did this mainly to learn the basics of Android programming, Java etc. It was fun and I partially completed my goal so I'm happy about it. If you don't have the time to review/debug this I'd completely understand. My guess is that the bug lies in the changes made to `app/src/main/java/zapsolutions/zap/fragments/SettingsFragment.java` since the code there was the most confusing.

### CODE REVIEW

**Comment by michaelWuensch** [comment]
Hi, thanks for your effort! Hope you had fun with it.
The reason for the crash is that you only added a bulgarian item on strings.xml which represents the english language.
As soon as you now change the language preference has now 3 value items (from the arrays.xml) but only 2 items in the translation (bulgarian strings.xml).

When I first made this, my idea was that the system language is standard and english as the reference language can be chosen if you want to do a tutorial or the translation is bad or unclear. 
But I now understand that some languages might be poorly supported by the operating system and therefore needs to be choosable directly.

What would be the ideal solution?
Making all the supported languages available in the list? Most of them are translated to 0% and would therefore look similar to english.
Or should we just mannually add those that at > 90 %?
Should the language names be translatable? (I would prefer no with the exception of "system language")

**Comment by michaelWuensch** [comment]
Hi Relaxo,
I now made a pull request, which should approach the problem you tried to fix on a broader basis by also including other languages.
Bulgarian translation is now available in the list. If you want to, you can test it and give feedback. :)

**Comment by Relaxo143** [comment]
> Hi, thanks for your effort! Hope you had fun with it.
> The reason for the crash is that you only added a bulgarian item on strings.xml which represents the english language.
> As soon as you now change the language preference has now 3 value items (from the arrays.xml) but only 2 items in the translation (bulgarian strings.xml).
> 
> When I first made this, my idea was that the system language is standard and english as the reference language can be chosen if you want to do a tutorial or the translation is bad or unclear.
> But I now understand that some languages might be poorly supported by the operating system and therefore needs to be choosable directly.
> 
> What would be the ideal solution?
> Making all the supported languages available in the list? Most of them are translated to 0% and would therefore look similar to english.
> Or should we just mannually add those that at > 90 %?
> Should the language names be translatable? (I would prefer no with the exception of "system language")

That's exactly what I had in mind. Since most of them are not fully translated we should manually add languages to the list with >90% completion and yes, I think the name of the language should be shown in the respective language as well. System Language can stay default and be written in English. Thank you for the explanation!

**Comment by michaelWuensch** [comment]
> That's exactly what I had in mind. Since most of them are not fully translated we should manually add languages to the list with >90% completion and yes, I think the name of the language should be shown in the respective language as well. System Language can stay default and be written in English. Thank you for the explanation!

I actually did it the other way around now. "system language" is translatable, but the language names are not.
First of all I thought it is annoying for translators to translate all the language names. Secondly I would never find "german" again if I switched to bulgarian language accidentally. And lastly, because we do not have to worry about missing language translations that could lead to the crashes like you had in your pull request.

**Comment by Relaxo143** [comment]
> > That's exactly what I had in mind. Since most of them are not fully translated we should manually add languages to the list with >90% completion and yes, I think the name of the language should be shown in the respective language as well. System Language can stay default and be written in English. Thank you for the explanation!
> 
> I actually did it the other way around now. "system language" is translatable, but the language names are not.
> First of all I thought it is annoying for translators to translate all the language names. Secondly I would never find "german" again if I switched to bulgarian language accidentally. And lastly, because we do not have to worry about missing language translations that could lead to the crashes like you had in your pull request.

I meant translatable as in Deutsch instead of German, Български instead of Bulgarian etc. It'd be stupid to translate "German" into Bulgarian, I agree.

**Comment by michaelWuensch** [comment]
Closing this pull request, as the other one got merged.

**Pull request closed without merging**
