### PR TITLE
Patch

### PR DESCRIPTION
**Pull request by M-BTC**
Added a few minor improvements

### CODE REVIEW

**Comment by michaelWuensch** [comment]
I am reposting my comment from your last Pull Request in case you have missed it.

@M-BTC Thanks a lot for your translation!
Our translations are organized using crowdin to keep it simple for people that have no experience in programming and git (https://crowdin.com/project/zap-android)
The translations have to be on crowdin as otherwise your translations would be overridden every time we fetch an update from crowdin.
I will manually import your translations now to crowdin. To keep it simple it would be awesome if you could make your future updates directly in crowdin.

That said, is it possible you redo those changes on crowdin?
Thanks!

**Comment by comradekingu** [comment]
@michaelWuensch Crowdin does a lot of spying, and helping their translation memory along doesn't isn't really the same as just sending it in here.

**Comment by michaelWuensch** [comment]
@comradekingua
As I said I am manually uploading the translations myself to crowdin after they are accepted here.
So you are still helping their translation memory.
I am not doing this as I love Crowdin so much, but because we don't want to maintain two different flows that override each other.

Now to the spying. What data do they have? 
An e-mail address, a password an IP address and translations.
For email and password you can use junk, to hide your ip you can use tor.
So they are left with translations.
I don't know what they could spy here. It's open source anyway. Everyone can see it.

You might not want to help them improve their algorithm for free, while they make money on it. That is a valid point. 
But I still think crowdin is a usefull service for a lot of people. 
And in 10 years you might have a new App in your language from the start, thanks to their algorithms. So in the long run this might be a win/win situation as well.

**Comment by M-BTC** [comment]
> That said, is it possible you redo those changes on crowdin?
> Thanks!

Making them now!

**Comment by michaelWuensch** [comment]
@M-BTC
Thank you very much! 
As it is done on crowdin now, I am closing this PR.

**Comment by comradekingu** [comment]
@michaelWuensch Weblate automatically does all of that for you. To be fair you could have done it on Crowdin too I think. If you send in a request on https://weblate.org/hosting/ they help you.
You would think that was all there is to it, but no https://github.com/jitsi/jitsi-meet/issues/5056#issuecomment-612239691
I really just wanted to show I am a genuine translator, as Crowdin has a campaign and history of wanting to dress itself up in the merit of libre software, when it has no business doing so.
If you get it set up I can help administer it, fix the source strings, and call in the translators I know for missing languages.

**Comment by michaelWuensch** [comment]
@comradekingu 
Thanks for your explanation.
Yes, maybe there is an automatic way in crowdin, too. But I am not a crowdin expert and just uploaded the file. (I didn't have to input every string manually)

I have never heard of Weblate before. Might actually be a better solution.
Zap Android started to use Crowdin, as all other Zap products already used it and the account was already payed for (or it is free, I even don't know that).
I will definetly have a closer look at Weblate now.

**Pull request closed without merging**
