### PR TITLE
I have updated the Italian translations

### PR DESCRIPTION
**Pull request by epicmario7133**
## Description

I have updated the Italian translations in app/src/main/res/values-it-rIT/strings.xml
## Motivation and Context
 People who don't speak Italian will understand what is written

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [Contribution document](../docs/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by michaelWuensch** [comment]
@epicmario7133 
thank you very much for your translations!
You are nearly completely done... can I ask you to translate the rest of the missing strings as well before merging?
The merging process is a bit complicated as we use crowdin for translations which you didn't use. If it was complete it would be easier and it would of course be more awesome for the italian users as well! :)

**Comment by epicmario7133** [comment]
Ok, I've updated all possible translations

**Comment by michaelWuensch** [comment]
@epicmario7133 
awesome.
I just wanted to merge it an saw there are still some strings missing.
Some of them might not need translation, but others do.

here are the missing ones:

missing strings

**Comment by epicmario7133** [comment]
> @epicmario7133
> awesome.
> I just wanted to merge it an saw there are still some strings missing.
> Some of them might not need translation, but others do.
> 
> here are the missing ones:
> 
> missing strings

@michaelWuensch  ok I added the missing translations, the following: privacy, host, Macaroon, Backup and tor do not have an Italian translation and English words are used in the spoken language

**Comment by michaelWuensch** [comment]
Wow, that was fast, thanks!

**Pull request merged**
